version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./:/frontend/
    networks:
      - frontend

networks:
  frontend:
    driver: "bridge"