services:

  postgres:
    restart: always
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_music_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -V" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}

  backend:
    restart: always
    container_name: backend
    build:
      context: backend
      dockerfile: "Dockerfile"
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/src

  migrations:
    container_name: migrations
    env_file:
      - .env
    build:
      context: backend
      dockerfile: "Dockerfile_migrations"
    depends_on:
      - postgres

volumes:
  postgres_music_volume:


