services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:8080"
    volumes:
      - "./nginx.conf:/etc/nginx/sites-enabled/seamusic"
    depends_on:
      - backend
      - frontend
    networks:
      - sm-prod
      
  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - sm-prod

  frontend:
    build:
      context: ./frontend
    networks:
      - sm-prod
      
networks:
  sm-prod:
