version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: tests
    image: postgres:16.2
    environment:
      - POSTGRES_DB=${DB_NAME_TEST}
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
    ports:
      - ${DB_PORT_TEST}:5432
    restart: always
    networks:
      - tests
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tests:
    driver: "bridge"