version: '3.8'

services:
  db:
    image: postgres:16.2
    container_name: my_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/backend/
    networks:
      - backend


  pgadmin:
    container_name: pgadmin_app
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'defaultemail@mail.ru'
      PGADMIN_DEFAULT_PASSWORD: '12345678'
    ports:
      - "5050:80"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
