"""fdsfdsfds

Revision ID: a9f846950e1b
Revises: 48ef6322880d
Create Date: 2024-05-09 15:39:31.024310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f846950e1b'
down_revision: Union[str, None] = '48ef6322880d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_to_beats_association_table_user_id_fkey', 'user_to_beats_association_table', type_='foreignkey')
    op.drop_constraint('user_to_beats_association_table_beat_id_fkey', 'user_to_beats_association_table', type_='foreignkey')
    op.create_foreign_key(None, 'user_to_beats_association_table', 'beats', ['beat_id'], ['id'])
    op.create_foreign_key(None, 'user_to_beats_association_table', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_to_beats_association_table', type_='foreignkey')
    op.drop_constraint(None, 'user_to_beats_association_table', type_='foreignkey')
    op.create_foreign_key('user_to_beats_association_table_beat_id_fkey', 'user_to_beats_association_table', 'users', ['beat_id'], ['id'])
    op.create_foreign_key('user_to_beats_association_table_user_id_fkey', 'user_to_beats_association_table', 'beats', ['user_id'], ['id'])
    # ### end Alembic commands ###
