"""empty message

Revision ID: af624a0e8579
Revises: 40e800f89180
Create Date: 2024-08-15 12:27:18.564446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af624a0e8579"
down_revision: Union[str, None] = "40e800f89180"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "licenses", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "licenses", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "licenses", type_="foreignkey")
    op.drop_column("licenses", "user_id")
    # ### end Alembic commands ###
