"""Inital

Revision ID: efa9f45a28d3
Revises: 
Create Date: 2024-06-22 16:00:58.871695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efa9f45a28d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlists')
    op.add_column('beats', sa.Column('picture_url', sa.String(), nullable=True))
    op.add_column('beats', sa.Column('file_url', sa.String(), nullable=False))
    op.drop_column('beats', 'picture')
    op.drop_column('beats', 'file_path')
    op.add_column('licenses', sa.Column('picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'picture_url')
    op.add_column('beats', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('beats', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('beats', 'file_url')
    op.drop_column('beats', 'picture_url')
    op.create_table('playlists',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='playlists_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='playlists_pkey')
    )
    # ### end Alembic commands ###
