"""fdsfdsfds

Revision ID: f8e6d47c98ee
Revises: 43fda0b39123
Create Date: 2024-05-09 16:11:30.516451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e6d47c98ee'
down_revision: Union[str, None] = '43fda0b39123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_beats_association_table')
    op.add_column('beats', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'beats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'beats', type_='foreignkey')
    op.drop_column('beats', 'user_id')
    op.create_table('user_to_beats_association_table',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('beat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], name='user_to_beats_association_table_beat_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_to_beats_association_table_user_id_fkey')
    )
    # ### end Alembic commands ###
