name: Clone Repositories

on:
  push:
    branches:
      - master

jobs:
  clone_repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: seamusic-official/seamusic-backend
          path: backend

      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          repository: seamusic-official/seamusic-frontend
          path: frontend
      
      - name: List files
        run: |
          echo "Files in backend:"
          ls backend
          echo "Files in frontend:"
          ls frontend
